theme = "dark_plus"
 
[editor]
true-color = true
line-number = "relative"
color-modes = true
cursorline = true
bufferline = "multiple"
preview-completion-insert = false

[editor.lsp]
auto-signature-help = true
display-messages = true

[editor.file-picker]
hidden = false
 
[editor.soft-wrap]
enable = true
 
[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "position", "file-type", "file-encoding", "version-control"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
 
[editor.cursor-shape]
insert="bar"

[editor.smart-tab]
enable = false
 
[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'<' = '>'

[keys.normal]
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]
"esc" = [ "normal_mode", ":format" ] # For quick saving
"left" = "goto_previous_buffer"
"right" = "goto_next_buffer"

[keys.select]
C-left = [ "move_prev_word_start", "move_char_left", "move_char_right" ]
C-right = [ "move_next_word_start", "move_char_left", "move_char_right" ]
